/*

 STARSYSTEM.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\denni\Documents\GitHub\StarTrader-Gameboy\gbdk\examples\gb\template_subfolders\res\StarsystemTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Starsystem_h_INCLUDE
#define __Starsystem_h_INCLUDE

#define StarsystemWidth 20
#define StarsystemHeight 18
#define StarsystemBank 0

extern const unsigned char Starsystem[];

#endif

/* End of STARSYSTEM.H */
