/*

 STARMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\gbdk\examples\gb\template_subfolders\res\StarmapTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Starmap_h_INCLUDE
#define __Starmap_h_INCLUDE

#define StarmapWidth 20
#define StarmapHeight 18
#define StarmapBank 0


extern const unsigned char Starmap[];


#endif

/* End of STARMAP.H */
